### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by Microsamp** [navopw/ConsoleReader#3]
https://github.com/navopw/ConsoleReader/blob/master/src/main/java/pw/navo/consolereader/ConsoleReader.java#L30
With StringTokenizer we could improve the performance by the factor 3

**Comment by navopw** [comment]
String.split() and StringTokenizer compared:
https://www.javamex.com/tutorials/regular_expressions/splitting_tokenisation_performance.shtml

> Using an Enumeration, as provided by StringTokenizer, is too "syntactically fussy" most of the time. From this point of view, StringTokenizer is a bit of a waste of space nowadays, and you may as well just use String.split().
